<?php

/**
 * Implementing hook_theme().
 */
function project_theme($existing, $type, $theme, $path) {

  return [
    // 2] set default variables [assuming they don't get reassigned]
    'goal' => [
      'variables' => [
        'goal' => [],
        'goalList' => [],
        'goalTheme' => "strongpartnerships",
        'numActions' => "0",
        'numProjects' => "0",
        'lastUpdated' => "",
      ]
    ],
    'objective' => [
      'variables' => [
        'goal' => [],
        'goalList' => [],
        'objective' => [],
        'goalTheme' => "strongpartnerships",
        'numActions' => "0",
        'numProjects' => "0",
        'lastUpdated' => "",
      ]
    ],
    'not_found' => [
      'variables' => [],
    ],
  ];
}
